package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	"github.com/jpoz/starter/pkg/env"
	"github.com/jpoz/starter/pkg/models"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	q := env.Query(ctx)

	return q.User.Where(q.User.ID.Eq(id)).First()
}
